[project]
name = "ai-proctor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.127.0",
    "mediapipe>=0.10.31",
    "opencv-python>=4.12.0.88",
    "pyyaml>=6.0.3",
    "rich>=14.2.0",
    "uvicorn>=0.40.0",
    "websockets>=14.1",
]
